### PR TITLE
Fix #197 jinja deprecation issues

### LINKED ISSUE #197: Jinja deprecation warnings
Warning summary:
```
=============================== warnings summary ===============================
test/test_admin.py::test_delete_user
  /__w/arch-security-tracker/arch-security-tracker/tracker/view/blueprint.py:42: DeprecationWarning: 'evalcontextfilter' is renamed to 'pass_eval_context', the old name will be removed in Jinja 3.1.
    def urlize(ctx, text, trim_url_limit=None, rel=None, target=None):

test/test_admin.py: 7 warnings
test/test_advisory.py: 4 warnings
test/test_cve.py: 13 warnings
test/test_group.py: 11 warnings
test/test_login.py: 4 warnings
test/test_profile.py: 4 warnings
  /usr/lib/python3.9/site-packages/flask_wtf/form.py:133: DeprecationWarning: 'jinja2.Markup' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.
    return Markup(

test/test_advisory.py: 12 warnings
  /__w/arch-security-tracker/arch-security-tracker/tracker/view/show.py:608: DeprecationWarning: 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.
    raw_asa = str(escape(raw_asa))

test/test_advisory.py: 17 warnings
test/test_cve.py: 23 warnings
test/test_group.py: 11 warnings
  /__w/arch-security-tracker/arch-security-tracker/tracker/view/blueprint.py:59: DeprecationWarning: 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.
    words = word_split_re.split(escape(text))

test/test_advisory.py: 17 warnings
test/test_cve.py: 23 warnings
test/test_group.py: 11 warnings
  /__w/arch-security-tracker/arch-security-tracker/tracker/view/blueprint.py:70: DeprecationWarning: 'jinja2.Markup' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.
    text = Markup(text)

test/test_advisory.py::test_advisory_published_html_content_escaped
test/test_advisory.py::test_advisory_published_content_not_overescaped
test/test_advisory.py::test_advisory_published_content_not_over_escaped
  /__w/arch-security-tracker/arch-security-tracker/tracker/advisory.py:87: DeprecationWarning: 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.
    advisory = advisory[:start_index] + str(html_escape(advisory[start_index:end_index])) + advisory[end_index:]

test/test_advisory.py::test_advisory_published_content_not_overescaped
  /__w/arch-security-tracker/arch-security-tracker/test/test_advisory.py:625: DeprecationWarning: 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.
    assert str(escape('<a href>')) not in data

test/test_advisory.py::test_advisory_generated_content_not_over_escaped
  /__w/arch-security-tracker/arch-security-tracker/test/test_advisory.py:636: DeprecationWarning: 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.
    assert str(escape('<a href')) not in data

test/test_advisory.py::test_advisory_published_content_not_over_escaped
  /__w/arch-security-tracker/arch-security-tracker/test/test_advisory.py:652: DeprecationWarning: 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.
    assert str(escape('<a href')) not in data
```

### PR DESCRIPTION
**Pull request by ysf**
Fixes the deprecation warnings of jinja2.markup, jinja2.escape and one regex that has not been upgraded to python3.

### CODE REVIEW

**Comment by jelly** [comment]
Looks good to me, I think we need to add an explicit dependency now on markupsafe in our readme, as although jinja depends on it now in the future it might not?

**Review by jelly — CHANGES_REQUESTED** [review]
Please include the (new) dependency [markupsafe](https://pypi.org/project/MarkupSafe/)

**Comment by ysf** [comment]
Since jinja2 and markupsafe are both from the same project and markupsafe has been refactored from jinja2 to an own project I think there would be needed to re-do some work around jinja2 and the tracker anyway if jinja2 should somehow remove this dependency.

that said: I'll add it to the files tomorrow as it won't hurt either.

**Comment by anthraxx** [comment]
@ysf we still need to change .github/workflows/test.yml as well, can you please do that and rebase against latest master?

**Comment by anthraxx** [comment]
applied via 0effc7403f1440449314529097cb92ad7827e081
thanks a lot

**Pull request closed without merging**
