### PR TITLE
feature(edit): optimistic locking of edit forms to avoid overwrites

### LINKED ISSUE #37: edit: optimistic locking of edit forms to avoid overwrites
We should implement optimistic locking for all edit forms to avoid overwrites by multiple people. While implementing the lock itself is easy, the more advanced question would be how to visualize the differences (new commited version) besides the preserved changes of the editor.

Some kind of content diffing and diff visualization would be appropriate to avoid dumping all data and let the user diff manually.

### PR DESCRIPTION
**Pull request by anthraxx**
Closes #37

### CODE REVIEW

**Review by diabonas — APPROVED** [review]
Very cool, I like the visualisation of the changes that happened in the meantime. The logic looks sane to me, I quickly tested doing conflicting edits of CVEs, AVGs and ASAs (including the "data has changed again while trying to perform a forced edit" scenario), all of which worked as expected.

**Review by SantiagoTorres — APPROVED** [review]
All in all this LGTM. I can test things properly and the logic seems to make sense. To add an alternative though: would it make sense to use an identifier for the content rather than a timestamp for concurrent detection? It seems to me that we aren't trying to detect concurrency in fact, but rather "has there been changes to the target since I last 'committed' them"? 

I would assume that this way we may save ourselves some time-drift clock-skew racyness sheananigans...

**Comment by anthraxx** [comment]
@SantiagoTorres Yes thats correct, i think its enough to detect if the data has changed in the meanwhile.

we just collect current time whenever the data is really change and afterwards just rely on representing it. there should be no influence from time-drift in this scenario as we also do not rely on any client side clocks. Do you think it would be worth changing everything?

**Comment by SantiagoTorres** [comment]
Thanks for bumping this up!

Nope, I think I'm comfortable with how things are now :)

**Pull request merged**
